### ISSUE TITLE
pnpm support

### ISSUE THREAD

**Issue by kauderk** [marko-js/run#20]
As of `"@marko/run": "^0.1.6"`
on build or dev commands

### Errors

<details><summary>When using the default example</summary>

https://github.com/marko-js/run/tree/main/examples/netlify

```json
{
  "name": "netlify-example",
  "version": "0.0.1",
  "type": "module",
  "scripts": {
    "build": "marko-run build",
    "dev": "marko-run",
    "start": "marko-run preview"
  },
  "devDependencies": {
    "@marko/compiler": "^5.22.6",
    "@marko/run": "^0.1.2",
    "@marko/run-adapter-netlify": "^0.1.0",
    "@marko/vite": "^2.3.7",
    "@types/compression": "^1.7.2",
    "@types/express": "^4.17.14",
    "@types/mocha": "^9.1.1",
    "@types/node": "^18.7.6",
    "prettier": "^2.7.1",
    "typescript": "^4.7.4",
    "vite": "^4.1.4"
  },
  "dependencies": {
    "marko": "^5.22.4"
  }
}
```

```bash
> marko-run build

[vite]: Rollup failed to resolve import ".pnpm/@marko+vite@2.4.0_w2m7nasiukek3x36vgnrkkf62e/node_modules/@marko/vite/dist/components/vite.marko" from "marko-run-netlify/__marko-run__special__500.marko?marko-server-entry".        
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
marko-run-netlify/node_modules/.pnpm/vite@4.3.1_@types+node@18.16.0/node_modules/vite/dist/node/chunks/dep-24daf00c.js:46525
                throw new Error(`[vite]: Rollup failed to resolve import "${exporter}" from "${id}".\n` +
                      ^

Error: [vite]: Rollup failed to resolve import ".pnpm/@marko+vite@2.4.0_w2m7nasiukek3x36vgnrkkf62e/node_modules/@marko/vite/dist/components/vite.marko" from "marko-run-netlify/__marko-run__special__500.marko?marko-server-entry". 
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (marko-run-netlify/node_modules/.pnpm/vite@4.3.1_@types+node@18.16.0/node_modules/vite/dist/node/chunks/dep-24daf00c.js:46525:23)
    at onRollupWarning (marko-run-netlify/node_modules/.pnpm/vite@4.3.1_@types+node@18.16.0/node_modules/vite/dist/node/chunks/dep-24daf00c.js:46549:9)
    at onwarn (marko-run-netlify/node_modules/.pnpm/vite@4.3.1_@types+node@18.16.0/node_modules/vite/dist/node/chunks/dep-24daf00c.js:46296:13)
    at Object.onwarn (marko-run-netlify/node_modules/.pnpm/rollup@3.21.0/node_modules/rollup/dist/es/shared/node-entry.js:25280:13)
    at ModuleLoader.handleInvalidResolvedId (marko-run-netlify/node_modules/.pnpm/rollup@3.21.0/node_modules/rollup/dist/es/shared/node-entry.js:23915:26)
    at marko-run-netlify/node_modules/.pnpm/rollup@3.21.0/node_modules/rollup/dist/es/shared/node-entry.js:23875:26 {
  watchFiles: [
	....
  ]
```
</details>

<br/>

<details><summary>When running `npm init marko -- -t basic` then adding vite</summary>

```json
{
  "name": "marko-meta",
  "description": "The default Marko starter app",
  "version": "1.0.0",
  "type": "module",
  "dependencies": {
    "marko": "^5"
  },
  "devDependencies": {
    "@marko/run": "^0.1.6",
    "@marko/run-adapter-netlify": "^0.1.3",
    "vite": "^4.3.1"
  },
  "private": true,
  "scripts": {
    "build": "marko-run build",
    "dev": "marko-run",
    "start": "marko-run preview"
  }
}
```
```bash
marko-run

10:43:01 PM [vite] Error when evaluating SSR module /node_modules/.pnpm/undici@5.22.0/node_modules/undici/index.js:
|- ReferenceError: require is not defined
    at eval (/node_modules/.pnpm/undici@5.22.0/node_modules/undici/index.js:5:16)
    at instantiateModule (marko-meta/node_modules/.pnpm/vite@4.3.1/node_modules/vite/dist/node/chunks/dep-24daf00c.js:54351:15)

10:43:02 PM [vite] Error when evaluating SSR module @marko/run/adapter/middleware: failed to import "/node_modules/.pnpm/undici@5.22.0/node_modules/undici/index.js"
|- ReferenceError: require is not defined
    at eval (/node_modules/.pnpm/undici@5.22.0/node_modules/undici/index.js:5:16)
    at instantiateModule (marko-meta/node_modules/.pnpm/vite@4.3.1/node_modules/vite/dist/node/chunks/dep-24daf00c.js:54351:15)

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

ReferenceError: require is not defined
    at eval (/node_modules/.pnpm/undici@5.22.0/node_modules/undici/index.js:5:16)
    at instantiateModule (marko-meta/node_modules/.pnpm/vite@4.3.1/node_modules/vite/dist/node/chunks/dep-24daf00c.js:54351:15)

Node.js v18.9.0
 ELIFECYCLE  Command failed with exit code 1.
```
</details>

**Comment by AngusMorton** [comment]
An .npmrc  file with `node-linker=hoisted` will let you use pnpm and Marko. See: https://pnpm.io/npmrc#node-linker.
