### ISSUE TITLE
Error: Could not resolve "@marko/runtime-tags/debug/dom"

### ISSUE THREAD

**Issue by stephenscaff** [marko-js/run#63]
### Details 

`npm run dev` results in the following Error

```
✘ [ERROR] Could not resolve "@marko/runtime-tags/debug/dom"
node_modules/marko/src/runtime/helpers/tags-compat/dom-debug.mjs:1:23:
      1 │ import { compat } from "@marko/runtime-tags/debug/dom";
        ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Attempting to visit local server will then produce:

```
[Error: ENOENT: no such file or directory, open '.../node_modules/@marko/run/.cache/explorer/data.json'
Rendered by getRoutes():
    at _marko_template$5._._marko_renderer.t (file:///.../node_modules/@marko/run-explorer/.app/index.mjs:506:3)
    at file:///.../node_modules/@marko/run-explorer/.app/index.mjs:694:5
    at _marko_template$6._._marko_renderer.t (file:///.../node_modules/@marko/run-explorer/.app/index.mjs:377:3)] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/.../node_modules/@marko/run/.cache/explorer/data.json'
}
```

Realize this is an issue further up the chain, but started here, so heads up.

### Screenshots

![Screenshot 2024-03-08 at 1 15 59 PM](https://github.com/marko-js/run/assets/4933525/16724a55-e72a-495a-be47-10e4979d2878)

**Comment by DylanPiercey** [comment]
This was addressed in recent marko release, forgot to close the issue though! Thanks for the report 😊
